name: 'CI'

on:
  push:
  
  pull_request:
    types:
      - opened
      - synchronize
  
  release:
    types:
      - created
  
  workflow_dispatch:

jobs:
  build:
    uses: a1hena/PluginRepository/.github/workflows/build.yaml@master
    with:
      plugin-name: 'IconBrowser'
    permissions:
      contents: read
      actions: write
  
  deploy:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    needs: build
    uses: a1hena/PluginRepository/.github/workflows/deploy.yaml@master
    with:
      plugin-name: 'IconBrowser'
    secrets:
      DEPLOY_GITHUB_TOKEN: '${{ secrets.GH_PAT }}'
    permissions:
      actions: read
